version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"
    environment:
      PLAYERS_IN_ROOM: "4"
      MAFIA_IN_ROOM: "1"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server