version: '3'

services:
  server:
    image: kaurker/mafia_server
    tty: true
    stdin_open: true
    expose:
      - "50051"
  
  client:
    image: kaurker/mafia_client
    tty: true
    stdin_open: true
    expose:
      - "50051"
    depends_on:
      - server